# Week 7 - Delta Lake MERGE Implementation

## Objective

The objective of this assignment is to perform data exploration and cleaning operations on the Superstore dataset and understand the basics of Delta Lake and MERGE operations.

## Tools Used

- Python
- Pandas
- PySpark
- VS Code Notebook
- Delta Lake


## Dataset Used

- Sample Superstore Dataset

## Tasks Performed

1. Load dataset.
2. Explore dataset structure.
3. Handle missing values.
4. Perform basic filtering and column selection.
5. Remove duplicate records.
6. Create derived columns.
7. Save cleaned dataset.
8. Prepare for Delta Lake MERGE operations.

## 1. Import Required Libraries

In [1]:
import pandas as pd

## 2. Load Dataset

In [3]:
df = pd.read_csv(
    "../data/SampleSuperstore.csv",
    encoding='latin1'
)

## 3. Explore Dataset
Before starting the cleaning assignment, as per the standard process i am analyzing the dataset.

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [6]:
df.shape

(9994, 21)

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [8]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

## 4. Important Insight
During implementation, I encountered a UnicodeDecodeError while reading the dataset. The issue was caused by incompatible file encoding. This was resolved by specifying the appropriate encoding format while loading the CSV file

### Observation 
I observed that the dataset contains multiple columns related to orders, customers, regions, and sales information.

## 5. Handling Missing Values

In [9]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [10]:
df.fillna(0, inplace=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

### Observation
Missing values were handled to ensure consistency during further processing.

## 6. Basic Operations
I performed basic filtering and column selection operations on the dataset.

In [11]:
tech_df = df[df["Category"]=="Technology"]
tech_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424,4,0.2,68.3568
19,20,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
26,27,CA-2016-121755,1/16/2016,1/20/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741
35,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737

In [12]:
selected_df = df[["Sales","Profit","Category"]]
selected_df.head()

      Sales    Profit         Category
0  261.9600   41.9136        Furniture
1  731.9400  219.5820        Furniture
2   14.6200    6.8714  Office Supplies
3  957.5775 -383.0310        Furniture
4   22.3680    2.5164  Office Supplies

## 7. Remove Duplicates

In [13]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

### Observation
Removed Duplicate records to maintain data quality.

## 8. Creating Derived Column

I created a new column using existing columns to generate additional information.

In [17]:
df["Discount_Amount"] = df["Sales"] * df["Discount"]
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount_Amount
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.000000
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.000000
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.000000
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,430.909875
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,4.473600

### Observation
A new column was created using existing columns to derive additional business information.

## 9. Save Cleaned Dataset

In [15]:
df.to_csv("../data/cleaned_superstore.csv", index=False)

## 10. Learning Outcome 
## Till Now

Through this exercise, I learned how to load datasets using Pandas, explore their structure, identify and handle missing values, perform filtering and column selection, remove duplicate records, create derived columns, and save cleaned datasets for further analysis.

## Delta Lake inclusion

## 11. Create Spark Session
SparkSession acts as the entry point for working with Spark DataFrames.

In [4]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Week7_DeltaLake") \
    .getOrCreate()

print("Spark Session Created Successfully")

Spark Session Created Successfully

In [5]:
spark

## 12. Create Existing Dataset - Target Table

In [6]:
target_data = [
    (101, "Rahul", "Delhi"),
    (102, "Aman", "Mumbai")
]

target_df = spark.createDataFrame(
    target_data,
    ["CustomerID", "Name", "City"]
)

target_df.show()

+----------+-----+------+
|CustomerID| Name|  City|
+----------+-----+------+
|       101|Rahul| Delhi|
|       102| Aman|Mumbai|
+----------+-----+------+

## 13. Create New Dataset - Source Table

In [7]:
source_data = [
    (101, "Rahul", "Noida"),
    (103, "Karan", "Pune")
]

source_df = spark.createDataFrame(
    source_data,
    ["CustomerID", "Name", "City"]
)

source_df.show()

+----------+-----+-----+
|CustomerID| Name| City|
+----------+-----+-----+
|       101|Rahul|Noida|
|       103|Karan| Pune|
+----------+-----+-----+

## Note 
 Since, I am currently learning the PySpark, and not have fully started Data Lake Package. So i am currently simulating MERGE using Spark. 
 Kindly consider this assignment, but i assure to fully complete the assignment within next week.

## 14. SPARK MERGE Logic

Step 1. Register Temp Views

In [8]:
target_df.createOrReplaceTempView("target")
source_df.createOrReplaceTempView("source")

In [9]:
spark

Step 2. Register Temp Views

In [10]:
target_df.createOrReplaceTempView("target")
source_df.createOrReplaceTempView("source")

Step 3. Execute MERGE Logic

In [11]:
merged_df = spark.sql("""
SELECT CustomerID, Name, City
FROM source

UNION ALL

SELECT t.CustomerID, t.Name, t.City
FROM target t
WHERE t.CustomerID NOT IN (
    SELECT CustomerID FROM source
)
""")

Step 4. Verify

In [12]:
merged_df.show()

+----------+-----+------+
|CustomerID| Name|  City|
+----------+-----+------+
|       101|Rahul| Noida|
|       103|Karan|  Pune|
|       102| Aman|Mumbai|
+----------+-----+------+

## 15. Observation

The merge logic which i used, successfully updated existing records and inserted new records from the source dataset. Spark SQL operations helped combine old and new data efficiently without manually modifying individual records.

This demonstrated the concept of UPSERT (Update + Insert), which is commonly performed using Delta Lake MERGE operations in modern data engineering workflows.

# 16. Learning Outcome

Through this assignment, I learned how to:

- Load and explore datasets using Pandas.
- Handle missing values and remove duplicate records.
- Create derived columns and save cleaned datasets.
- Create Spark DataFrames.
- Understand the concept of target and source tables.
- Apply merge logic using Spark SQL.
- Understand how Delta Lake MERGE performs update and insert operations.
- Appreciate the role of Spark in scalable data processing workflows.